# docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    container_name: econyang-db
    environment:
      POSTGRES_DB: econyang
      POSTGRES_USER: econyang_user
      POSTGRES_PASSWORD: your-secure-password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U econyang_user -d econyang"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: econyang-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: