spring:
  config:
    activate:
      on-profile: dev,prod

# RSS 피드 소스 설정
rss:
  sources:
    - name: "BBC Business"
      url: "http://feeds.bbci.co.uk/news/business/rss.xml"
      enabled: true
      category: "국제경제"
      updateIntervalMinutes: 15
      priority: 1
    - name: "Financial Times"
      url: "https://www.ft.com/companies?format=rss"
      enabled: true
      category: "기업/금융"
      updateIntervalMinutes: 15
      priority: 1
    - name: "MarketWatch"
      url: "http://feeds.marketwatch.com/marketwatch/topstories/"
      enabled: true
      category: "시장동향"
      updateIntervalMinutes: 15
      priority: 2
    - name: "Bloomberg Economics"
      url: "https://feeds.bloomberg.com/economics/news.rss"
      enabled: true
      category: "경제분석"
      updateIntervalMinutes: 15
      priority: 1
    - name: "The Economist"
      url: "https://www.economist.com/economics/rss.xml"
      enabled: true
      category: "경제분석"
      updateIntervalMinutes: 30
      priority: 1
    - name: "Investing.com News"
      url: "https://kr.investing.com/rss/news.rss"
      enabled: true
      category: "투자정보"
      updateIntervalMinutes: 15
      priority: 2
    - name: "Investing.com Market Overview"
      url: "https://kr.investing.com/rss/market_overview.rss"
      enabled: true
      category: "시장동향"
      updateIntervalMinutes: 15
      priority: 2
    - name: "Investing.com Commodities"
      url: "https://kr.investing.com/rss/commodities.rss"
      enabled: true
      category: "원자재"
      updateIntervalMinutes: 30
      priority: 3
    - name: "KOTRA 해외시장뉴스"
      url: "https://dream.kotra.or.kr/kotra/rssList.do?pBbsGroup=1"
      enabled: true
      category: "해외시장"
      updateIntervalMinutes: 60
      priority: 2
    - name: "매일경제 증권"
      url: "https://www.mk.co.kr/rss/30800011/"
      enabled: true
      category: "증권/주식"
      updateIntervalMinutes: 15
      priority: 3

  # 키워드 필터 설정
  filters:
    # 포함되어야 할 키워드 (OR 조건 - 영어 & 한국어)
    includeKeywords:
      # 영어 키워드
      - "economy"
      - "business" 
      - "finance"
      - "investment"
      - "market"
      - "stock"
      - "trading"
      - "earnings"
      - "revenue"
      - "profit"
      - "GDP"
      - "inflation"
      - "interest rate"
      - "federal reserve"
      - "central bank"
      - "merger"
      - "acquisition"
      - "IPO"
      - "corporate"
      - "financial"
      - "economic"
      - "fiscal"
      - "monetary"
      - "trade"
      - "export"
      - "import"
      - "currency"
      - "exchange rate"
      - "banking"
      - "securities"
      - "commodities"
      - "Fed"
      - "ECB"
      - "dollar"
      - "oil"
      - "gold"
      - "Bitcoin"
      - "cryptocurrency"
      - "blockchain"
      - "AI"
      - "artificial intelligence"
      - "technology"
      - "startup"
      - "unicorn"
      - "venture"
      - "ESG"
      - "carbon neutral"
      - "green deal"
      - "digital"
      # 한국어 키워드
      - "경제"
      - "금융"
      - "투자"
      - "시장"
      - "주식"
      - "증권"
      - "금리"
      - "환율"
      - "무역"
      - "수출"
      - "수입"
      - "기업"
      - "원자재"
      - "인플레이션"
      - "수출입"
      - "주가"
      - "코스피"
      - "코스닥"
      - "부동산"
      - "아파트"
      - "집값"
      - "은행"
      - "펀드"
      - "채권"
      - "산업"
      - "제조업"
      - "서비스업"
      - "반도체"
      - "자동차"
      - "에너지"
      - "유가"
      - "국제유가"
      - "달러"
      - "원달러"
      - "중앙은행"
      - "한국은행"
      - "연준"
      - "일본은행"
      - "중국인민은행"
      - "물가"
      - "소비"
      - "소비자물가"
      - "생산자물가"
      - "고용"
      - "실업"
      - "실업률"
      - "취업"
      - "일자리"
      - "임금"
      - "최저임금"
      - "세금"
      - "세율"
      - "법인세"
      - "소득세"
      - "부가세"
      - "관세"
      - "예산"
      - "국가예산"
      - "재정"
      - "국채"
      - "회사채"
      - "상장"
      - "인수합병"
      - "구조조정"
      - "부도"
      - "워크아웃"
      - "신용등급"
      - "신용평가"
      - "무디스"
      - "스타트업"
      - "유니콘"
      - "벤처"
      - "경기침체"
      - "경기회복"
      - "인공지능"
      - "블록체인"
      - "비트코인"
      - "가상화폐"
      - "암호화폐"
      - "메타버스"
      - "탄소중립"
      - "그린뉴딜"
      - "디지털뉴딜"

    # 제외할 키워드 (AND 조건 - 영어 & 한국어)
    excludeKeywords:
      # 영어 키워드
      - "sports"
      - "entertainment"
      - "celebrity"
      - "weather" 
      - "crime"
      - "accident"
      - "politics"
      - "election"
      - "gaming"
      - "lifestyle"
      - "health"
      - "medical"
      - "hospital"
      - "disease"
      - "vaccine"
      - "treatment"
      - "diet"
      - "fitness"
      - "exercise"
      - "movie"
      - "music"
      - "drama"
      - "actor"
      - "singer"
      - "earthquake"
      - "fire"
      - "murder"
      - "robbery" 
      - "theft"
      - "traffic accident"
      - "doctor"
      - "nurse"
      - "patient"
      # 한국어 키워드
      - "스포츠"
      - "연예"
      - "오락"
      - "게임"
      - "드라마"
      - "영화"
      - "음악"
      - "아이돌"
      - "연예인"
      - "배우"
      - "가수"
      - "날씨"
      - "기상"
      - "태풍"
      - "지진"
      - "화재"
      - "사고"
      - "범죄"
      - "살인"
      - "강도"
      - "절도"
      - "교통사고"
      - "의료"
      - "병원"
      - "의사"
      - "간호사"
      - "환자"
      - "질병"
      - "백신"
      - "치료제"
      - "건강"
      - "다이어트"
      - "운동"
      - "피트니스"
      - "정치"
      - "선거"

    # 최소 제목 길이 (문자 수)
    minTitleLength: 10
    
    # 최대 제목 길이 (문자 수)
    maxTitleLength: 200

  # RSS 수집 설정
  collection:
    # 최대 기사 수 (소스별)
    maxArticlesPerSource: 50
    
    # 연결 타임아웃 (초)
    connectionTimeoutSec: 10
    
    # 읽기 타임아웃 (초)
    readTimeoutSec: 30
    
    # 재시도 횟수
    maxRetries: 3
    
    # 재시도 간격 (밀리초)
    retryDelayMs: 2000
    
    # User-Agent 설정
    userAgent: "EconDigest-RSS-Bot/1.0 (+https://github.com/yourco/econdigest)"
    
    # 중복 제거 설정
    deduplication:
      # URL 기반 중복 제거 활성화
      enableUrlDedup: true
      
      # 제목 유사도 기반 중복 제거 활성화
      enableTitleDedup: true
      
      # 제목 유사도 임계값 (0.0 ~ 1.0)
      titleSimilarityThreshold: 0.85
      
      # 같은 소스에서 중복 제거만 할지 여부
      dedupWithinSourceOnly: false

  # 시간 설정
  time:
    # 기본 시간대
    defaultTimeZone: "Asia/Seoul"
    
    # 최대 기사 나이 (시간)
    maxArticleAgeHours: 72
    
    # 날짜 파싱 형식들
    dateFormats:
      - "yyyy-MM-dd'T'HH:mm:ss'Z'"
      - "yyyy-MM-dd'T'HH:mm:ssXXX"
      - "EEE, dd MMM yyyy HH:mm:ss zzz"
      - "yyyy-MM-dd HH:mm:ss"
      - "yyyy-MM-dd"

---
spring:
  profiles: test

# 테스트용 설정
rss:
  sources:
    - name: "테스트소스1"
      url: "https://example.com/rss1.xml"
      enabled: true
      category: "테스트"
      updateIntervalMinutes: 5
      priority: 1
    - name: "테스트소스2"
      url: "https://example.com/rss2.xml"
      enabled: true
      category: "테스트"
      updateIntervalMinutes: 5
      priority: 2

  filters:
    includeKeywords:
      - "경제"
      - "테스트"
    excludeKeywords:
      - "광고"
    minTitleLength: 5
    maxTitleLength: 100

  collection:
    maxArticlesPerSource: 10
    connectionTimeoutSec: 5
    readTimeoutSec: 10
    maxRetries: 2
    retryDelayMs: 1000
    userAgent: "EconDigest-Test-Bot/1.0"
    deduplication:
      enableUrlDedup: true
      enableTitleDedup: true
      titleSimilarityThreshold: 0.9
      dedupWithinSourceOnly: true

  time:
    defaultTimeZone: "Asia/Seoul"
    maxArticleAgeHours: 24
    dateFormats:
      - "yyyy-MM-dd'T'HH:mm:ss'Z'"
      - "EEE, dd MMM yyyy HH:mm:ss zzz"