spring:
  config:
    activate:
      on-profile: dev,prod

# RSS 피드 소스 설정
rss:
  sources:
    - name: "BBC Business"
      code: "bbc_business"
      url: "https://feeds.bbci.co.uk/news/business/rss.xml"
      enabled: true
      category: "국제경제"
      updateIntervalMinutes: 15
      priority: 1
    - name: "Financial Times"
      code: "ft_companies"
      url: "https://www.ft.com/companies?format=rss"
      enabled: true
      category: "기업/금융"
      updateIntervalMinutes: 15
      priority: 1
    - name: "MarketWatch"
      code: "marketwatch"
      url: "https://feeds.content.dowjones.io/public/rss/mw_topstories"
      enabled: true
      category: "시장동향"
      updateIntervalMinutes: 15
      priority: 2
    - name: "Bloomberg Economics"
      code: "bloomberg_economics"
      url: "https://feeds.bloomberg.com/economics/news.rss"
      enabled: true
      category: "경제분석"
      updateIntervalMinutes: 15
      priority: 1
    - name: "Investing.com 주식시장"
      code: "investing_stock"
      url: "https://kr.investing.com/rss/news_25.rss"
      enabled: true
      category: "주식시장"
      updateIntervalMinutes: 15
      priority: 2
    - name: "Investing.com 경제지표"
      code: "investing_economic"
      url: "https://kr.investing.com/rss/news_95.rss"
      enabled: true
      category: "경제지표"
      updateIntervalMinutes: 15
      priority: 2
    - name: "Investing.com 금융뉴스"
      code: "investing_finance"
      url: "https://kr.investing.com/rss/news.rss"
      enabled: true
      category: "금융뉴스"
      updateIntervalMinutes: 15
      priority: 2
    - name: "Investing.com 실적보고"
      code: "investing_earnings"
      url: "https://kr.investing.com/rss/news_1062.rss"
      enabled: true
      category: "실적보고"
      updateIntervalMinutes: 30
      priority: 3
    - name: "KOTRA 해외시장뉴스"
      code: "kotra_overseas"
      url: "https://dream.kotra.or.kr/kotra/rssList.do?pBbsGroup=1"
      enabled: true
      category: "해외시장"
      updateIntervalMinutes: 60
      priority: 2
    - name: "매일경제 증권"
      code: "maeil_securities"
      url: "https://www.mk.co.kr/rss/30800011/"
      enabled: true
      category: "증권/주식"
      updateIntervalMinutes: 15
      priority: 3

  # 키워드 필터 설정 - 주식시장과 거시경제 중심
  filters:
    # 핵심 경제 키워드 (OR 조건 - 하나라도 포함되어야 함)
    includeKeywords:
      # === 주식시장 관련 ===
      - "stock"
      - "stocks" 
      - "equity"
      - "shares"
      - "market"
      - "markets"
      - "trading"
      - "earnings"
      - "revenue"
      - "profit"
      - "IPO"
      - "listing"
      - "dividend"
      - "buyback"
      - "valuation"
      - "P/E"
      - "EPS"
      - "bull market"
      - "bear market"
      - "S&P 500"
      - "Nasdaq"
      - "Dow Jones"
      - "NYSE"
      
      # === 거시경제 지표 ===
      - "GDP"
      - "inflation"
      - "CPI"
      - "PPI"
      - "unemployment"
      - "employment"
      - "jobs report"
      - "payroll"
      - "interest rate"
      - "federal reserve"
      - "Fed"
      - "central bank"
      - "monetary policy"
      - "fiscal policy"
      - "QE"
      - "quantitative easing"
      - "recession"
      - "growth"
      - "economic data"
      - "consumer confidence"
      - "retail sales"
      - "industrial production"
      
      # === 금융시장 ===
      - "bond"
      - "bonds"
      - "treasury"
      - "yield"
      - "yield curve"
      - "credit"
      - "banking"
      - "financial sector"
      - "currency"
      - "exchange rate"
      - "dollar"
      - "euro"
      - "yen"
      
      # === 허용 투자 자산 ===
      - "real estate"
      - "REIT"
      - "gold"
      - "silver"
      - "commodities"
      - "oil"
      - "crude"
      - "copper"
      - "agricultural"
      
      # === 기업 실적/M&A ===
      - "merger"
      - "acquisition"
      - "corporate earnings"
      - "quarterly results"
      - "guidance"
      - "outlook"
      - "restructuring"
      # === 한국어 주식시장 ===
      - "주식"
      - "증권"
      - "주가"
      - "코스피"
      - "코스닥" 
      - "유가증권"
      - "상장"
      - "기업공개"
      - "배당"
      - "자사주"
      - "실적"
      - "영업이익"
      - "순이익"
      - "매출"
      - "PER"
      - "EPS"
      - "ROE"
      
      # === 한국어 거시경제 ===
      - "경제"
      - "GDP"
      - "경제성장률"
      - "물가"
      - "인플레이션"
      - "소비자물가"
      - "생산자물가"
      - "기준금리"
      - "금리"
      - "한국은행"
      - "중앙은행"
      - "연준"
      - "통화정책"
      - "재정정책"
      - "양적완화"
      - "경기침체"
      - "경기회복"
      - "고용"
      - "실업률"
      - "취업률"
      
      # === 한국어 금융시장 ===
      - "금융"
      - "은행"
      - "채권"
      - "국채"
      - "회사채"
      - "수익률"
      - "금융시장"
      - "환율"
      - "원달러"
      - "달러"
      - "외환"
      
      # === 한국어 허용 투자자산 ===
      - "부동산"
      - "리츠"
      - "금"
      - "원자재"
      - "유가"
      - "국제유가"
      - "구리"
      - "농산물"
      
      # === 한국어 기업/투자 ===
      - "투자"
      - "기업"
      - "인수합병"
      - "M&A"
      - "구조조정"
      - "신용등급"
      - "펀드"

    # 제외할 키워드 - 경제와 무관한 뉴스 필터링 강화
    excludeKeywords:
      # === 엔터테인먼트/문화 ===
      - "sports"
      - "entertainment" 
      - "celebrity"
      - "movie"
      - "film"
      - "music"
      - "drama"
      - "actor"
      - "actress"
      - "singer"
      - "concert"
      - "album"
      - "gaming"
      - "game"
      - "esports"
      - "streaming"
      - "Netflix"
      - "Disney"
      
      # === 정치/사회 ===
      - "politics"
      - "political"
      - "election"
      - "vote"
      - "campaign"
      - "government" 
      - "congress"
      - "senate"
      - "parliament"
      - "minister"
      - "president"
      - "prime minister"
      - "legislation"
      - "law"
      - "legal"
      - "court"
      - "judge"
      
      # === 기술/개인용품 (투자와 무관) ===
      - "smartphone"
      - "iPhone"
      - "Samsung Galaxy"
      - "Android"
      - "apps"
      - "social media"
      - "Facebook"
      - "Instagram"
      - "Twitter"
      - "TikTok"
      - "gaming console"
      - "PlayStation"
      - "Xbox"
      
      # === 건강/의료 ===
      - "health"
      - "medical"
      - "hospital"
      - "doctor"
      - "nurse"
      - "patient"
      - "disease"
      - "virus"
      - "vaccine"
      - "treatment"
      - "medicine"
      - "drug"
      - "surgery"
      - "diet"
      - "fitness"
      - "exercise"
      - "wellness"
      
      # === 사건사고 ===
      - "crime"
      - "accident"
      - "murder"
      - "robbery"
      - "theft"
      - "fire"
      - "earthquake"
      - "disaster"
      - "weather"
      - "storm"
      - "flood"
      - "hurricane"
      
      # === 라이프스타일 ===
      - "lifestyle"
      - "fashion"
      - "beauty"
      - "travel"
      - "tourism"
      - "restaurant"
      - "food"
      - "cooking"
      - "recipe"
      - "wedding"
      - "marriage"
      - "divorce"
      # === 한국어 엔터테인먼트/문화 ===
      - "스포츠"
      - "연예"
      - "오락"
      - "게임"
      - "드라마"
      - "영화"
      - "음악"
      - "아이돌"
      - "연예인"
      - "배우"
      - "가수"
      - "예능"
      - "방송"
      - "콘서트"
      - "앨범"
      - "K-POP"
      - "BTS"
      - "블랙핑크"
      - "넷플릭스"
      - "유튜브"
      
      # === 한국어 정치/사회 ===
      - "정치"
      - "선거"
      - "투표"
      - "국회"
      - "의원"
      - "장관"
      - "대통령"
      - "총리"
      - "정부"
      - "정당"
      - "법원"
      - "판사"
      - "검사"
      - "변호사"
      - "재판"
      - "소송"
      - "법안"
      - "법률"
      
      # === 한국어 건강/의료 ===
      - "건강"
      - "의료"
      - "병원"
      - "의사"
      - "간호사"
      - "환자"
      - "질병"
      - "바이러스"
      - "백신"
      - "치료"
      - "약"
      - "수술"
      - "다이어트"
      - "운동"
      - "헬스"
      - "피트니스"
      - "요가"
      
      # === 한국어 사건사고 ===
      - "사건"
      - "사고"
      - "화재"
      - "지진"
      - "태풍"
      - "홍수"
      - "재해"
      - "날씨"
      - "기상"
      - "살인"
      - "강도"
      - "절도"
      - "교통사고"
      
      # === 한국어 라이프스타일 ===
      - "패션"
      - "뷰티"
      - "화장품"
      - "여행"
      - "관광"
      - "맛집"
      - "음식"
      - "요리"
      - "레시피"
      - "결혼"
      - "이혼"
      - "육아"
      - "교육"
      - "학교"
      - "대학"
      - "입시"
      
      # === 한국어 기타 비경제 ===
      - "종교"
      - "교회"
      - "절"
      - "목사"
      - "스님"
      - "애완동물"
      - "반려동물"
      - "고양이"
      - "강아지"
      - "태풍"
      - "지진"
      - "화재"
      - "사고"
      - "범죄"
      - "살인"
      - "강도"
      - "절도"
      - "교통사고"
      - "의료"
      - "병원"
      - "의사"
      - "간호사"
      - "환자"
      - "질병"
      - "백신"
      - "치료제"
      - "건강"
      - "다이어트"
      - "운동"
      - "피트니스"
      - "정치"
      - "선거"

    # 최소 제목 길이 (문자 수)
    minTitleLength: 10
    
    # 최대 제목 길이 (문자 수)
    maxTitleLength: 200

  # RSS 수집 설정
  collection:
    # 최대 기사 수 (소스별)
    maxArticlesPerSource: 50
    
    # 연결 타임아웃 (초)
    connectionTimeoutSec: 10
    
    # 읽기 타임아웃 (초)
    readTimeoutSec: 30
    
    # 재시도 횟수
    maxRetries: 3
    
    # 재시도 간격 (밀리초)
    retryDelayMs: 2000
    
    # User-Agent 설정
    userAgent: "EconDigest-RSS-Bot/1.0 (+https://github.com/yourco/econdigest)"
    
    # 중복 제거 설정
    deduplication:
      # URL 기반 중복 제거 활성화
      enableUrlDedup: true
      
      # 제목 유사도 기반 중복 제거 활성화
      enableTitleDedup: true
      
      # 제목 유사도 임계값 (0.0 ~ 1.0)
      titleSimilarityThreshold: 0.85
      
      # 같은 소스에서 중복 제거만 할지 여부
      dedupWithinSourceOnly: false

  # 시간 설정
  time:
    # 기본 시간대
    defaultTimeZone: "Asia/Seoul"
    
    # 최대 기사 나이 (시간)
    maxArticleAgeHours: 96
    
    # 날짜 파싱 형식들
    dateFormats:
      - "yyyy-MM-dd'T'HH:mm:ss'Z'"
      - "yyyy-MM-dd'T'HH:mm:ssXXX"
      - "EEE, dd MMM yyyy HH:mm:ss zzz"
      - "yyyy-MM-dd HH:mm:ss"
      - "yyyy-MM-dd"

---
spring:
  profiles: test

# 테스트용 설정
rss:
  sources:
    - name: "테스트소스1"
      url: "https://example.com/rss1.xml"
      enabled: true
      category: "테스트"
      updateIntervalMinutes: 5
      priority: 1
    - name: "테스트소스2"
      url: "https://example.com/rss2.xml"
      enabled: true
      category: "테스트"
      updateIntervalMinutes: 5
      priority: 2

  filters:
    includeKeywords:
      - "경제"
      - "테스트"
    excludeKeywords:
      - "광고"
    minTitleLength: 5
    maxTitleLength: 100

  collection:
    maxArticlesPerSource: 10
    connectionTimeoutSec: 5
    readTimeoutSec: 10
    maxRetries: 2
    retryDelayMs: 1000
    userAgent: "EconDigest-Test-Bot/1.0"
    deduplication:
      enableUrlDedup: true
      enableTitleDedup: true
      titleSimilarityThreshold: 0.9
      dedupWithinSourceOnly: true

  time:
    defaultTimeZone: "Asia/Seoul"
    maxArticleAgeHours: 24
    dateFormats:
      - "yyyy-MM-dd'T'HH:mm:ss'Z'"
      - "EEE, dd MMM yyyy HH:mm:ss zzz"