-- H2 compatible schema for testing
-- Removes PostgreSQL-specific data types and constraints

CREATE TABLE articles (
    id bigint generated by default as identity,
    author varchar(255),
    content clob,
    created_at timestamp,
    extract_error varchar(255),
    extracted_at timestamp,
    published_at timestamp,
    raw_excerpt varchar(255),
    source varchar(255) not null,
    title varchar(255) not null,
    url varchar(255) not null,
    primary key (id)
);

CREATE TABLE daily_digest (
    id bigint generated by default as identity,
    body_markdown clob not null,
    created_at timestamp,
    digest_date date not null,
    title varchar(255) not null,
    total_articles integer,
    total_summaries integer,
    updated_at timestamp,
    primary key (id)
);

CREATE TABLE dispatch_log (
    id bigint generated by default as identity,
    attempt_count integer,
    channel varchar(255) not null,
    created_at timestamp,
    error_message clob,
    response_snippet clob,
    status varchar(255) not null,
    webhook_ref varchar(255),
    digest_id bigint not null,
    primary key (id)
);

CREATE TABLE summaries (
    id bigint generated by default as identity,
    bullets clob, -- H2 doesn't support arrays, use JSON string instead
    created_at timestamp,
    evidence_idx clob, -- H2 doesn't support int arrays, use JSON string instead
    glossary clob, -- H2 doesn't support jsonb, use clob
    model varchar(255) not null,
    score decimal(10,4),
    summary_text varchar(255) not null,
    why_it_matters varchar(255) not null,
    article_id bigint not null,
    primary key (id)
);

-- Add foreign keys
ALTER TABLE dispatch_log ADD CONSTRAINT fk_dispatch_log_digest_id FOREIGN KEY (digest_id) REFERENCES daily_digest (id);
ALTER TABLE summaries ADD CONSTRAINT fk_summaries_article_id FOREIGN KEY (article_id) REFERENCES articles (id);

-- Add unique constraints for business logic
ALTER TABLE articles ADD CONSTRAINT uk_articles_url UNIQUE (url);
ALTER TABLE summaries ADD CONSTRAINT uk_summaries_article_model UNIQUE (article_id, model);